spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:mysql://localhost:3308/schooldiary
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: admin
rsa:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem